version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  database:
    image: postgres:13.0-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
  predictor:
    build: ./predictor
    command: python manage.py run -h 0.0.0.0 -p ${PREDICTOR_PORT}
    volumes:
      - ./predictor/:/usr/src/app/
    ports:
      - ${PREDICTOR_PORT}:${PREDICTOR_PORT}
    env_file:
      - ./.env

volumes:
  db_data:

